apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defualt-standard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  # selector:
  #   matchLabels:
  #     app: pv-app