apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defualt-standard-pvc
  labels:
    app: dynmaic-provising-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  