apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    app: pv-app
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/k8s-pv-data