apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: capstone
Data:
  WORDPRESS_DB_HOST: mysql-statefulset-0.mysql-service.capstone.svc.cluster.local:3306
  WORDPRESS_DB_NAME: capstone_db