kind: Secret
apiVersion: v1
metadata:
  name: db-secret
  namespace: capstone
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: capstone_db
  MYSQL_USER: capstone_user
  MYSQL_PASSWORD: cap@123