apiVersion: v1
kind: Pod
metadata:
  name: pending-pod-app
spec:
  containers:
  - name: pending-app
    image: nginx:1.29
    resources:
      requests:
        memory: "128Gi"
        cpu: "100"
      limits:
        memory: "128Gi"
        cpu: "100"