apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  containers:
  - name: app
    image: nginx:1.29
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"