apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-multi-lbl
  labels:
    app: nginx-app
    environment: production
    team: backend
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80