kind: Pod
apiVersion: v1

metadata:
  name: busybox-pod
  labels:
    app: busybox-label

spec:
  containers:
    - name: busybox-cont
      image: busybox:latest
      command: ["sh", "-c" , "echo Hello from BusyBox && sleep 120"]

  