kind: Service
apiVersion: v1

metadata:
  name: flask-app-service
  namespace: flask-app-ns

spec:
  selector:
    app: flask-app-label
  ports:
    - protocol: TCP
    # this is conatiner port
      port: 80
    # this is service port
      targetPort: 80
  